# Generated by Django 3.2.7 on 2021-09-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvAPI', '0003_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvuser',
            name='image_url',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
